[workspace]
resolver = "3"
members = [
  "engine",
  "common",
  "crates/core/renderer/api",
  "crates/core/renderer/backend/vulkan",
]

[profile.release]
opt-level = 3
debug-assertions = false
overflow-checks = false

[profile.release-with-debug]
inherits = "release"
debug-assertions = true
overflow-checks = true
debug = 1

[profile.release-with-full-debug]
inherits = "release"
debug-assertions = true
overflow-checks = true
debug = 2

[alias]
release-with-debug      = "run --profile release-with-debug -p wolf-engine"
release-with-full-debug = "run --profile release-with-full-debug -p wolf-engine"
