[workspace]
resolver = "3"
members = [
  "engine",
  "common",
  "crates/core/renderer/api",
  "crates/core/renderer/backend/vulkan",
]

[workspace.package]
edition = "2024"
version = "0.1.0"

[workspace.dependencies]
winit       = "*"
env_logger  = "*"
log         = "*"
libloading  = "*"
vulkanalia  = "*"
smallvec    = "*" 

common         = { path = "common" }
renderer-api   = { path = "crates/core/renderer/api" }
backend-vulkan = { path = "crates/core/renderer/backend/vulkan" }

[profile.release]
opt-level = 3
debug-assertions = false
overflow-checks = false

[profile.release-with-debug]
inherits = "release"
debug-assertions = true
overflow-checks = true
debug = 1

[profile.release-with-full-debug]
inherits = "release"
debug-assertions = true
overflow-checks = true
debug = 2
