[package]
name    = "wolf-engine"
version = "0.1.0"
edition = "2024"

[dependencies]
vulkanalia = { version = "*", features = ["window", "libloading"] }
winit      = "*"
log        = "*"
env_logger = "*"
libloading = "*"
