[package]
name    = "backend-vulkan"
version = "0.1.0"
edition = "2024"

[dependencies]
common       = { path = "../../../../../common", features = ["vulkan", "libloading", "winit"] }
renderer-api = { path = "../../api" }

smallvec          = "*"
log               = "*"
winit             = "*"
vulkanalia        = { version = "*", features = ["window", "libloading"] }
libloading        = "*"
