[package]
name    = "common"
version = "0.1.0"
edition = "2024"

[features]
# Keep base crate dependency-free; enable converters only when needed.
winit      = ["dep:winit"]
libloading = ["dep:libloading"]
vulkan     = ["dep:vulkanalia"]

[dependencies]
# Optional deps, pulled only if a crate enables the feature.
winit       = { version = "*",    optional = true }
libloading  = { version = "*",    optional = true }
vulkanalia  = { version = "*",    optional = true }
